import type { Metadata } from "next";
import localFont from "next/font/local";
import style from "./layout.module.css";
import Navigation from "@/widget/navigate";
import Layout from "@/widget/layout";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={style.main_container}>
          <div className={style.app_container}>
            <Navigation />
            <div className={style.inner}>
              <Layout />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
