import type { Metadata } from "next";
import style from "./layout.module.css";
import Navigation from "@/widget/navigate";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={style.main_container}>
          <div className={style.app_container}>
            <Navigation />
            <div className={style.inner}>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
